.TH "Duz" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Duz \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strukture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBvratiIdDuzi\fP ()"
.br
.ti -1c
.RI "void \fBpostaviIDDuzi\fP (int idDuzi)"
.br
.ti -1c
.RI "bool \fBjelOznacena\fP ()"
.br
.ti -1c
.RI "void \fBoznaciDuz\fP ()"
.br
.ti -1c
.RI "void \fBponistiOznacenuDuz\fP ()"
.br
.ti -1c
.RI "int \fBvratiPocetnuKoordinatu\fP (int d)"
.br
.ti -1c
.RI "QPoint \fBvratiPocetnuKoordinatu\fP ()"
.br
.ti -1c
.RI "QPoint \fBvratiKrajnjuKoordinatu\fP ()"
.br
.ti -1c
.RI "int \fBvratiKrajnjuKoordinatu\fP (int d)"
.br
.ti -1c
.RI "void \fBpostaviPocetnuKoordinatu\fP (QPoint pocetnaKoord)"
.br
.ti -1c
.RI "void \fBpostaviKrajnjuKoordinatu\fP (QPoint krajnjaKoord)"
.br
.ti -1c
.RI "int \fBvratiIdDuzi\fP ()"
.br
.RI "\fIIdentifikacija duzi\&. \fP"
.ti -1c
.RI "void \fBpostaviIDDuzi\fP (int idDuzi)"
.br
.ti -1c
.RI "bool \fBjelOznacena\fP ()"
.br
.ti -1c
.RI "void \fBoznaciDuz\fP ()"
.br
.ti -1c
.RI "void \fBponistiOznacenuDuz\fP ()"
.br
.ti -1c
.RI "int \fBvratiPocetnuKoordinatu\fP (int d)"
.br
.ti -1c
.RI "QPoint \fBvratiPocetnuKoordinatu\fP ()"
.br
.ti -1c
.RI "QPoint \fBvratiKrajnjuKoordinatu\fP ()"
.br
.ti -1c
.RI "int \fBvratiKrajnjuKoordinatu\fP (int d)"
.br
.ti -1c
.RI "void \fBpostaviPocetnuKoordinatu\fP (QPoint pocetnaKoord)"
.br
.ti -1c
.RI "void \fBpostaviKrajnjuKoordinatu\fP (QPoint krajnjaKoord)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file strukture\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Duz::jelOznacena ()\fC [inline]\fP"

.PP
Definition at line 23 of file strukture\&.h\&.
.SS "bool Duz::jelOznacena ()\fC [inline]\fP"

.PP
Definition at line 24 of file strukture\&.h\&.
.SS "void Duz::oznaciDuz ()\fC [inline]\fP"

.PP
Definition at line 26 of file strukture\&.h\&.
.SS "void Duz::oznaciDuz ()\fC [inline]\fP"

.PP
Definition at line 27 of file strukture\&.h\&.
.SS "void Duz::ponistiOznacenuDuz ()\fC [inline]\fP"

.PP
Definition at line 29 of file strukture\&.h\&.
.SS "void Duz::ponistiOznacenuDuz ()\fC [inline]\fP"

.PP
Definition at line 30 of file strukture\&.h\&.
.SS "void Duz::postaviIDDuzi (intidDuzi)\fC [inline]\fP"

.PP
Definition at line 20 of file strukture\&.h\&.
.SS "void Duz::postaviIDDuzi (intidDuzi)\fC [inline]\fP"

.PP
Definition at line 21 of file strukture\&.h\&.
.SS "void Duz::postaviKrajnjuKoordinatu (QPointkrajnjaKoord)\fC [inline]\fP"

.PP
Definition at line 71 of file strukture\&.h\&.
.SS "void Duz::postaviKrajnjuKoordinatu (QPointkrajnjaKoord)\fC [inline]\fP"

.PP
Definition at line 72 of file strukture\&.h\&.
.SS "void Duz::postaviPocetnuKoordinatu (QPointpocetnaKoord)\fC [inline]\fP"

.PP
Definition at line 68 of file strukture\&.h\&.
.SS "void Duz::postaviPocetnuKoordinatu (QPointpocetnaKoord)\fC [inline]\fP"

.PP
Definition at line 69 of file strukture\&.h\&.
.SS "int Duz::vratiIdDuzi ()\fC [inline]\fP"

.PP
Definition at line 18 of file strukture\&.h\&.
.SS "int Duz::vratiIdDuzi ()\fC [inline]\fP"

.PP
Identifikacija duzi\&. 
.PP
Definition at line 19 of file strukture\&.h\&.
.SS "QPoint Duz::vratiKrajnjuKoordinatu ()\fC [inline]\fP"

.PP
Definition at line 50 of file strukture\&.h\&.
.SS "QPoint Duz::vratiKrajnjuKoordinatu ()\fC [inline]\fP"

.PP
Definition at line 51 of file strukture\&.h\&.
.SS "int Duz::vratiKrajnjuKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 53 of file strukture\&.h\&.
.SS "int Duz::vratiKrajnjuKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 54 of file strukture\&.h\&.
.SS "int Duz::vratiPocetnuKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 32 of file strukture\&.h\&.
.SS "int Duz::vratiPocetnuKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 33 of file strukture\&.h\&.
.SS "QPoint Duz::vratiPocetnuKoordinatu ()\fC [inline]\fP"

.PP
Definition at line 47 of file strukture\&.h\&.
.SS "QPoint Duz::vratiPocetnuKoordinatu ()\fC [inline]\fP"

.PP
Definition at line 48 of file strukture\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
