.TH "ElementarniInterval" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementarniInterval \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strukture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpostaviInterval\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBpostaviInterval\fP (int x, int y)"
.br
.RI "\fIKoordinata kraja intervala\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpocetak\fP"
.br
.ti -1c
.RI "int \fBkraj\fP"
.br
.RI "\fIKoordinata pocetka intervala\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file strukture\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void ElementarniInterval::postaviInterval (intx, inty)\fC [inline]\fP"

.PP
Definition at line 124 of file strukture\&.h\&.
.SS "void ElementarniInterval::postaviInterval (intx, inty)\fC [inline]\fP"

.PP
Koordinata kraja intervala\&. 
.PP
Definition at line 127 of file strukture\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ElementarniInterval::kraj"

.PP
Koordinata pocetka intervala\&. 
.PP
Definition at line 122 of file strukture\&.h\&.
.SS "int ElementarniInterval::pocetak"

.PP
Definition at line 121 of file strukture\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
