.TH "KrajnjaTackaDuzi" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KrajnjaTackaDuzi \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strukture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBvratiIdDuzi\fP ()"
.br
.ti -1c
.RI "int \fBvratiKoordinatu\fP (int d)"
.br
.ti -1c
.RI "void \fBpostaviKoordinatu\fP (QPoint koordinata)"
.br
.ti -1c
.RI "void \fBpostaviIdDuzi\fP (int idDuzi)"
.br
.ti -1c
.RI "int \fBvratiIdDuzi\fP ()"
.br
.RI "\fIvarijabla u kojoj cuvamo informaciji o identifikaciji duzi \fP"
.ti -1c
.RI "int \fBvratiKoordinatu\fP (int d)"
.br
.ti -1c
.RI "void \fBpostaviKoordinatu\fP (QPoint koordinata)"
.br
.ti -1c
.RI "void \fBpostaviIdDuzi\fP (int idDuzi)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file strukture\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void KrajnjaTackaDuzi::postaviIdDuzi (intidDuzi)\fC [inline]\fP"

.PP
Definition at line 109 of file strukture\&.h\&.
.SS "void KrajnjaTackaDuzi::postaviIdDuzi (intidDuzi)\fC [inline]\fP"

.PP
Definition at line 110 of file strukture\&.h\&.
.SS "void KrajnjaTackaDuzi::postaviKoordinatu (QPointkoordinata)\fC [inline]\fP"

.PP
Definition at line 106 of file strukture\&.h\&.
.SS "void KrajnjaTackaDuzi::postaviKoordinatu (QPointkoordinata)\fC [inline]\fP"

.PP
Definition at line 107 of file strukture\&.h\&.
.SS "int KrajnjaTackaDuzi::vratiIdDuzi ()\fC [inline]\fP"

.PP
Definition at line 88 of file strukture\&.h\&.
.SS "int KrajnjaTackaDuzi::vratiIdDuzi ()\fC [inline]\fP"

.PP
varijabla u kojoj cuvamo informaciji o identifikaciji duzi 
.PP
Definition at line 89 of file strukture\&.h\&.
.SS "int KrajnjaTackaDuzi::vratiKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 91 of file strukture\&.h\&.
.SS "int KrajnjaTackaDuzi::vratiKoordinatu (intd)\fC [inline]\fP"

.PP
Definition at line 92 of file strukture\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
