.TH "PoredjenjePoY" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoredjenjePoY \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strukture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBKrajnjaTackaDuzi\fP &t1, const \fBKrajnjaTackaDuzi\fP &t2)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBKrajnjaTackaDuzi\fP &t1, const \fBKrajnjaTackaDuzi\fP &t2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file strukture\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PoredjenjePoY::operator() (const \fBKrajnjaTackaDuzi\fP &t1, const \fBKrajnjaTackaDuzi\fP &t2)\fC [inline]\fP"

.PP
Definition at line 152 of file strukture\&.h\&.
.SS "bool PoredjenjePoY::operator() (const \fBKrajnjaTackaDuzi\fP &t1, const \fBKrajnjaTackaDuzi\fP &t2)\fC [inline]\fP"

.PP
Definition at line 155 of file strukture\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
