.TH "PoredjenjePoVrijednostiPresjeka" 3 "Wed Aug 28 2013" "Magistarski rad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoredjenjePoVrijednostiPresjeka \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stablo_duzi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBStabloDuzi::AsocijativniCvor\fP &a_cvor1, const \fBStabloDuzi::AsocijativniCvor\fP &a_cvor2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 231 of file stablo_duzi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PoredjenjePoVrijednostiPresjeka::operator() (const \fBStabloDuzi::AsocijativniCvor\fP &a_cvor1, const \fBStabloDuzi::AsocijativniCvor\fP &a_cvor2)\fC [inline]\fP"

.PP
Definition at line 233 of file stablo_duzi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski rad from the source code\&.
