.TH "pretraga_raspona.h" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pretraga_raspona.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QVectorIterator>\fP
.br
\fC#include 'strukture\&.h'\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QRubberBand>\fP
.br
\fC#include <QMouseEvent>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QAction>\fP
.br
\fC#include <QtGui/QApplication>\fP
.br
\fC#include <QtGui/QButtonGroup>\fP
.br
\fC#include <QtGui/QHeaderView>\fP
.br
\fC#include <QtGui/QMainWindow>\fP
.br
\fC#include <QtGui/QMenu>\fP
.br
\fC#include <QtGui/QMenuBar>\fP
.br
\fC#include <QtGui/QStatusBar>\fP
.br
\fC#include <QtGui/QToolBar>\fP
.br
\fC#include <QtGui/QWidget>\fP
.br
\fC#include <QtAlgorithms>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'stablo_raspona\&.h'\fP
.br
\fC#include 'stablo_duzi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPretragaProstora\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNEGBESKONACNO\fP   -5000"
.br
.ti -1c
.RI "#define \fBPOZBESKONACNO\fP   +5000"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstate\fP { \fBCEKANJA\fP, \fBPRETRAGA\fP, \fBCRTANJA1\fP, \fBCRTANJA2\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NEGBESKONACNO   -5000"

.PP
Definition at line 31 of file pretraga_raspona\&.h\&.
.SS "#define POZBESKONACNO   +5000"

.PP
Definition at line 32 of file pretraga_raspona\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstate\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICEKANJA \fP\fP
.TP
\fB\fIPRETRAGA \fP\fP
.TP
\fB\fICRTANJA1 \fP\fP
.TP
\fB\fICRTANJA2 \fP\fP
.PP
Definition at line 37 of file pretraga_raspona\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
