.TH "GeneratedFiles/qrc_resursi.cpp" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneratedFiles/qrc_resursi.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QT_BEGIN_NAMESPACE 
.br
Q_CORE_EXPORT bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "Q_CORE_EXPORT bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "QT_END_NAMESPACE int 
.br
QT_MANGLE_NAMESPACE() \fBqInitResources_resursi\fP ()"
.br
.ti -1c
.RI "int QT_MANGLE_NAMESPACE() \fBqCleanupResources_resursi\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int QT_MANGLE_NAMESPACE() qCleanupResources_resursi ()"

.PP
Definition at line 1058 of file qrc_resursi\&.cpp\&.
.SS "QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_resursi ()"

.PP
Definition at line 1049 of file qrc_resursi\&.cpp\&.
.SS "QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SS "Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
