.TH "resource.h" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resource.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIDB_BITMAP1\fP   101"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IDB_BITMAP1   101"

.PP
Definition at line 5 of file resource\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
