.TH "StabloDuzi::AsocijativniCvor" 3 "Wed Aug 28 2013" "Magistarski rad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StabloDuzi::AsocijativniCvor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stablo_duzi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpostaviVrijednost\fP (int v)"
.br
.RI "\fIVrijednost presjeka granicne prave sa duzi koju ispitujemo\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBElementarniInterval\fP \fBm_elementarni_interval\fP"
.br
.ti -1c
.RI "int \fBidDuzi\fP"
.br
.RI "\fIElementarni intervali duzi\&. \fP"
.ti -1c
.RI "int \fBvrijednostPresjeka\fP"
.br
.RI "\fIIdentifikacija duzi\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file stablo_duzi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void StabloDuzi::AsocijativniCvor::postaviVrijednost (intv)\fC [inline]\fP"

.PP
Vrijednost presjeka granicne prave sa duzi koju ispitujemo\&. 
.PP
Definition at line 38 of file stablo_duzi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int StabloDuzi::AsocijativniCvor::idDuzi"

.PP
Elementarni intervali duzi\&. 
.PP
Definition at line 29 of file stablo_duzi\&.h\&.
.SS "\fBElementarniInterval\fP StabloDuzi::AsocijativniCvor::m_elementarni_interval"

.PP
Definition at line 28 of file stablo_duzi\&.h\&.
.SS "int StabloDuzi::AsocijativniCvor::vrijednostPresjeka"

.PP
Identifikacija duzi\&. 
.PP
Definition at line 30 of file stablo_duzi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski rad from the source code\&.
