.TH "StabloDuzi" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StabloDuzi \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stablo_duzi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStabloDuzi\fP (QVector< \fBKrajnjaTackaDuzi\fP > tacke, int dimenzija, QVector< \fBDuz\fP > vekDuzi)"
.br
.ti -1c
.RI "\fBStabloDuzi\fP ()"
.br
.ti -1c
.RI "void \fBpretraziStabloDuzi\fP (int ispitna_vrijednost, int pocetak, int kraj, QVector< \fBDuz\fP > &vekDuzi, int dimenzija)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file stablo_duzi\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StabloDuzi::StabloDuzi (QVector< \fBKrajnjaTackaDuzi\fP >tacke, intdimenzija, QVector< \fBDuz\fP >vekDuzi)"

.PP
Definition at line 3 of file stablo_duzi\&.cpp\&.
.SS "StabloDuzi::StabloDuzi ()\fC [inline]\fP"

.PP
Definition at line 226 of file stablo_duzi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void StabloDuzi::pretraziStabloDuzi (intispitna_vrijednost, intpocetak, intkraj, QVector< \fBDuz\fP > &vekDuzi, intdimenzija)"

.PP
Definition at line 429 of file stablo_duzi\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
