.TH "strukture.h" 3 "Sat Aug 31 2013" "Version 1" "Magistarski aplikacija" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strukture.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QPoint>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDuz\fP"
.br
.ti -1c
.RI "struct \fBKrajnjaTackaDuzi\fP"
.br
.ti -1c
.RI "struct \fBElementarniInterval\fP"
.br
.ti -1c
.RI "struct \fBPoredjenjePoX\fP"
.br
.ti -1c
.RI "struct \fBPoredjenjePoY\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Magistarski aplikacija from the source code\&.
